# Assignment 1.2: Word2vec preprocessing (20 points)

Preprocessing is not the most exciting part of NLP, but it is still one of the most important ones. Your task is to preprocess raw text (you can use your own, or [this one](http://mattmahoney.net/dc/text8.zip). For this task text preprocessing mostly consists of:

1. cleaning (mostly, if your dataset is from social media or parsed from the internet)
1. tokenization
1. building the vocabulary and choosing its size. Use only high-frequency words, change all other words to UNK or handle it in your own manner. You can use `collections.Counter` for that.
1. assigning each token a number (numericalization). In other words, make word2index и index2word objects.
1. data structuring and batching - make X and y matrices generator for word2vec (explained in more details below)

**ATTN!:** If you use your own data, please, attach a download link. 

Your goal is to make **Batcher** class which returns two numpy tensors with word indices. It should be possible to use one for word2vec training. You can implement batcher for Skip-Gram or CBOW architecture, the picture below can be helpful to remember the difference.

![text](https://raw.githubusercontent.com/deepmipt/deep-nlp-seminars/651804899d05b96fc72b9474404fab330365ca09/seminar_02/pics/architecture.png)

There are several ways to do it right. Shapes could be `x_batch.shape = (batch_size, 2*window_size)`, `y_batch.shape = (batch_size,)` for CBOW or `(batch_size,)`, `(batch_size, 2*window_size)` for Skip-Gram. You should **not** do negative sampling here.

They should be adequately parametrized: CBOW(window_size, ...), SkipGram(window_size, ...). You should implement only one batcher in this task; and it's up to you which one to chose.

Useful links:
1. [Word2Vec Tutorial - The Skip-Gram Model](http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/)
1. [Efficient Estimation of Word Representations in Vector Space](https://arxiv.org/pdf/1301.3781.pdf)
1. [Distributed Representations of Words and Phrases and their Compositionality](http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf)

You can write the code in this notebook, or in a separate file. It can be reused for the next task. The result of your work should represent that your batch has a proper structure (right shapes) and content (words should be from one context, not some random indices). To show that, translate indices back to words and print them to show something like this:

```
text = ['first', 'used', 'against', 'early', 'working', 'class', 'radicals', 'including']

window_size = 2

# CBOW:
indices_to_words(x_batch) = \
        [['first', 'used', 'early', 'working'],
        ['used', 'against', 'working', 'class'],
        ['against', 'early', 'class', 'radicals'],
        ['early', 'working', 'radicals', 'including']]

indices_to_words(labels_batch) = ['against', 'early', 'working', 'class']
```

In [121]:
import gc
import string
import re
from collections import Counter
import numpy as np
gc.collect()

2814

In [202]:
class Batcher:
    def __init__(self, window_size, corpus_path, min_freq, max_freq, max_voc_size, batch_size):
        self.corpus_path = corpus_path
        self.window_size = window_size
        self.min_freq = min_freq
        self.max_freq = max_freq
        self.max_voc_size = max_voc_size
        self.batch_size = batch_size
        self.words = None
        self.word2index = None
        self.index2word = None
        self.freq = None
        self.voc = None
        self.corpus = None
        self.corpus_size = None
        
        
    def read_data(self, S):
        if S == None:
            with open(self.corpus_path, 'r') as f:
                S = f.read()
            S = S.lower()[:1000000]
        print('Len of S = ', len(S))
        regex = re.compile('[%s]' % re.escape(string.punctuation))
        S = regex.sub(' ', S)
        words = list(S.split())
        self.words = words
        unique_words = list(set(words))
        self.word2index = {k: v for v, k in enumerate(unique_words)}
        self.word2index['UNK'] = -1
        self.index2word = {v: k for v, k in enumerate(unique_words)}
        self.index2word[-1] = 'UNK'
        words = [self.word2index[word] for word in words]
        
        print('Size of words = ', len(words))
        counter = Counter(words)
        print('Size of counter = ', len(counter))
        if self.min_freq != None:
            counter = {x : counter[x] for x in counter if counter[x] >= self.min_freq}
        print('Size of counter after min_freq = ', len(counter))
        if self.max_freq != None:
            counter = {x : counter[x] for x in counter if counter[x] <= self.max_freq}
        print('Size of counter after max_freq = ', len(counter))
        counter = Counter(counter)

        self.freq = dict(counter.most_common(self.max_voc_size))
        self.voc = set(self.freq)
        unk = set(words).difference(self.voc)
        print('Size of freq dict = ', len(self.voc))
        print('Number of vocabulary words = ', len(self.voc))
        print('Number of unknown words = ', len(unk))

        words = [-1 if word in unk else word for word in words]
        
        if len(words)%self.batch_size == 0:
            padding = self.window_size
        else:
            padding = self.batch_size - len(words)%self.batch_size + self.window_size
            
        self.corpus = [-2]*self.window_size + words + [-2]*padding
        self.corpus_size = len(self.corpus)
            
    def generator(self):
        i = self.window_size
        x_batch = []
        y_batch = []
        
        while i < self.corpus_size-self.window_size:
            if len(x_batch)==self.batch_size:
                x_batch = []
                y_batch = []
                
            x = self.corpus[i-self.window_size: i] + self.corpus[i+1: i+self.window_size+1]
            y = [self.corpus[i]]
            x_batch.append(x)
            y_batch.append(y)
            i += 1
            if len(x_batch)==self.batch_size:
                yield np.array(x_batch), np.array(y_batch)

In [206]:
batcher = Batcher(window_size=2, corpus_path='text8', min_freq=2, max_freq=100, max_voc_size=1000000, batch_size=5)
batcher.read_data(S=None)

Len of S =  1000000
Size of words =  167285
Size of counter =  16774
Size of counter after min_freq =  8851
Size of counter after max_freq =  8691
Size of freq dict =  8691
Number of vocabulary words =  8691
Number of unknown words =  8083


In [207]:
print(batcher.corpus)

[-2, -2, -1, 6201, -1, -1, 1418, -1, 7696, -1, -1, 1699, -1, 12436, 13246, 6616, -1, -1, 925, -1, -1, 16516, 13781, -1, -1, -1, -1, -1, -1, 5311, 13781, 797, -1, 1418, -1, 1392, -1, -1, -1, -1, 1757, -1, 14451, 4420, 4317, -1, -1, 10458, 1059, -1, 16425, -1, 7906, -1, 13409, -1, -1, -1, -1, 11395, -1, -1, -1, 15826, 5887, -1, 6146, 4310, 2028, -1, 1235, -1, -1, 12709, -1, -1, 14408, 9104, -1, 15921, 8426, 12136, -1, -1, -1, 12756, -1, -1, -1, 11589, -1, 8734, -1, 4252, -1, 5700, -1, 6791, -1, -1, -1, 12175, 10012, -1, -1, -1, 1059, -1, -1, 12371, -1, 8332, -1, 6095, -1, 8909, -1, -1, -1, 2644, 14476, 13447, -1, -1, -1, 1235, 8807, -1, -1, 2028, -1, -1, 4194, -1, 851, 6827, 13402, -1, -1, -1, 13568, -1, -1, 9250, 2644, 13409, -1, 15890, -1, -1, -1, 5275, -1, 2644, 12756, 639, -1, -1, 3768, 14476, 2028, 8909, -1, 1216, 9558, 12118, 3006, 13569, -1, 3343, 5192, 13017, 13730, -1, 6146, 8440, -1, -1, -1, -1, 4069, 4310, -1, -1, -1, -1, 1699, 2028, -1, 8367, 15826, -1, -1, -1, -1, 2879, -1, 

In [208]:
i = 0
for x, y in batcher.generator():
    i += 1

In [209]:
x

array([[ 9059,  8389,    -1,    -1],
       [ 8389,  3219,    -1,    -1],
       [ 3219,    -1,    -1, 15841],
       [   -1,    -1, 15841,    -2],
       [   -1,    -1,    -2,    -2]])

In [210]:
y

array([[ 3219],
       [   -1],
       [   -1],
       [   -1],
       [15841]])

In [203]:
batcher = Batcher(window_size=2, corpus_path='text8', min_freq=None, max_freq=None, max_voc_size=1000000, batch_size=1)
batcher.read_data(S='first used against early working class radicals including')

Len of S =  57
Size of words =  8
Size of counter =  8
Size of counter after min_freq =  8
Size of counter after max_freq =  8
Size of freq dict =  8
Number of vocabulary words =  8
Number of unknown words =  0


In [204]:
print(batcher.corpus)

[-2, -2, 6, 3, 1, 5, 2, 7, 4, 0, -2, -2]


In [205]:
i = 0
for x, y in batcher.generator():
    print(x)
    print(y)
    i += 1

[[-2 -2  3  1]]
[[6]]
[[-2  6  1  5]]
[[3]]
[[6 3 5 2]]
[[1]]
[[3 1 2 7]]
[[5]]
[[1 5 7 4]]
[[2]]
[[5 2 4 0]]
[[7]]
[[ 2  7  0 -2]]
[[4]]
[[ 7  4 -2 -2]]
[[0]]
